[tool.poetry]
name = "censusviz"
version = "0.1.0"
description = "A Python package to make it easier to visualize Census data."
authors = ["Elliott <eat2153@columbia.edu>"]
license = "MIT"

[tool.poetry.dependencies]
python = "^3.8"

[tool.poetry.dev-dependencies]

[build-system]
requires = ["poetry>=0.12"]
build-backend = "poetry.masonry.api"
